### ISSUE TITLE
Select a day of the week

### ISSUE THREAD

**Issue by BrendanBTO** [longztian/chrome_extensions#1]
I see the script refreshing the page every few seconds. Since I don't see it selecting today, and each of the next two days. I assume it would only be able to reserve a time for same day. Any ability to check each of the 3 days?

**Comment by lzztt** [comment]
It selects the first (next) available time from all the available time options the page presents. The next available time could be the same day, or tomorrow, or a week later.

**Comment by BrendanBTO** [comment]
Thanks that makes sense. What about items going out of stock? I've been running it for a few hours and I saw a prompt about an item that went out of stock. Is the script able to acknowledge the removal of out of stock items and continue running?

**Comment by lzztt** [comment]
Costco/Instacart will remove out-of-stock items at a later (purchase/delivery) time. Whole Foods/Amazon Fresh may redirect to a different page to about out-of-stock items.
The extension will stop checking and refreshing the page if the page is redirected to a different page from the delivery selection page. The extension doesn't handle this as the redirection doesn't happen often.

**Comment by BrendanBTO** [comment]
OK so I'll just check periodically to make sure it didn't redirect to the out of stock page. 

What happens when it does find a delivery time? I saw the icon of a dog. So I proceeded thru to the checkout. Is there any auto checkout option? In my area you have to be very very quick to secure a delivery when one becomes available.

**Comment by lzztt** [comment]
It will choose the first delivery time and click the "Continue" button. The page will go the next step of the checkout.
Auto checkout is complicated, as different stores have different checkout steps. For Amazon, sometime it will ask you to confirm the address or payment method before the final checkout review&confirmation page.

**Comment by BrendanBTO** [comment]
OK that's what I saw it did for me. How about the notifications. Is there an audible sound that's supposed to play on your PC to alert you? I'm running this on a virtual desktop actually so I'm not sure whether I'd even hear the audible alert if there is one.

**Comment by lzztt** [comment]
It relies on the OS notification sound.
From README: 
> (Optional) Turn on the notification sound for Chrome ([macOS howto](https://support.apple.com/en-us/HT204079))
